//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class actualizarMoraDaria
    {
        public string Codigo { get; set; }
        public int NroCuota { get; set; }
        public Nullable<int> diasAtraso { get; set; }
        public double MontoCuota { get; set; }
        public decimal porcentaje { get; set; }
        public Nullable<double> InteresMora { get; set; }
        public string Doc { get; set; }
        public string CodigoCtaxcobrarDet { get; set; }
        public string CodCliente { get; set; }
    }
}
