//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmMovImportacion
    {
        public int CodSucursal { get; set; }
        public string Comprobante { get; set; }
        public string TipoMov { get; set; }
        public string CodProdD { get; set; }
        public int CodALmD { get; set; }
        public string CodCli { get; set; }
        public string NroNota { get; set; }
        public int CodCalidad { get; set; }
        public int CodVenCom { get; set; }
        public System.DateTime Fec { get; set; }
        public System.DateTime Hor { get; set; }
        public string Concepto { get; set; }
        public double CanIngreso { get; set; }
        public double CanEgreso { get; set; }
        public double Prec { get; set; }
        public double PrecBs { get; set; }
        public double PrecUFV { get; set; }
        public double Volumen { get; set; }
        public double Peso { get; set; }
        public double CSeguroS { get; set; }
        public double CSeguroB { get; set; }
        public double CTranspTS { get; set; }
        public double CTranspTB { get; set; }
        public double GPuertoS { get; set; }
        public double GPuertoB { get; set; }
        public double CTranspPS { get; set; }
        public double CTranspPB { get; set; }
        public double CTranspFS { get; set; }
        public double CTranspFB { get; set; }
        public double OGastoB { get; set; }
        public double OGastoS { get; set; }
        public double GastosNacSus { get; set; }
        public double GastosNacBs { get; set; }
        public double ComisiónAgencia { get; set; }
        public double GastosDespacho { get; set; }
        public string CodUsuario { get; set; }
        public System.DateTime FecReg { get; set; }
        public string Obs { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
