//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmTraspasoAlmInterno
    {
        public string IndTraspAlm { get; set; }
        public int CodSucursal { get; set; }
        public string IndTraspZF { get; set; }
        public int CodAlmSale { get; set; }
        public int CodAlmIng { get; set; }
        public int Moneda { get; set; }
        public System.DateTime FecTrasp { get; set; }
        public System.DateTime HorTrasp { get; set; }
        public double TC { get; set; }
        public string IdEncargado { get; set; }
        public string Glosa { get; set; }
        public string NroEquipo { get; set; }
        public int Prorrateo { get; set; }
        public double DerechoAduana { get; set; }
        public double ImpRenta { get; set; }
        public double ImpEspecifico { get; set; }
        public double Almacenaje { get; set; }
        public double Levantamiento { get; set; }
        public double GastoPuerto { get; set; }
        public double Fletes { get; set; }
        public double Descargo { get; set; }
        public double Transporte { get; set; }
        public double CamaraCo { get; set; }
        public double CamaraDesp { get; set; }
        public double Fotocopias { get; set; }
        public double Poliza { get; set; }
        public double DocYValorados { get; set; }
        public double Tramites { get; set; }
        public double Movilizacion { get; set; }
        public double Dicomex { get; set; }
        public double CertificadoFitosanitario { get; set; }
        public double CamaraForestal { get; set; }
        public double FormUnicoExport { get; set; }
        public double Frontera { get; set; }
        public double Formulario151 { get; set; }
        public double FacturaReexpedicion { get; set; }
        public double Cadex { get; set; }
        public double SobreCarro { get; set; }
        public double CapturaInformatica { get; set; }
        public double ComisionAgencia { get; set; }
        public double GastosDespacho { get; set; }
        public string CodProveedor { get; set; }
        public string CodProvDescarguio { get; set; }
        public double DescarguioSus { get; set; }
        public double DescarguioBs { get; set; }
        public string CodProvOtrosG { get; set; }
        public double OtrosGSus { get; set; }
        public double OtrosGBs { get; set; }
        public double Verificacion { get; set; }
        public string NroDUI { get; set; }
        public System.DateTime FechaDUI { get; set; }
        public int ComprDiario { get; set; }
        public string CodGestion { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaReg { get; set; }
        public int F_Almacenaje { get; set; }
        public int F_Levantamiento { get; set; }
        public int F_GastoPuerto { get; set; }
        public int F_Fletes { get; set; }
        public int F_Descargo { get; set; }
        public int F_Transporte { get; set; }
        public int F_CamaraCo { get; set; }
        public int F_CamaraDesp { get; set; }
        public int F_Fotocopias { get; set; }
        public int F_Poliza { get; set; }
        public int F_DocYValorados { get; set; }
        public int F_Tramites { get; set; }
        public int F_Movilizacion { get; set; }
        public int F_Dicomex { get; set; }
        public int F_CertFitosanitario { get; set; }
        public int F_CamaraForestal { get; set; }
        public int F_FormUnicoExport { get; set; }
        public int F_Frontera { get; set; }
        public int F_Formulario151 { get; set; }
        public int F_FacturaReexpedicion { get; set; }
        public int F_Cadex { get; set; }
        public int F_SobreCarro { get; set; }
        public int F_CapturaInformatica { get; set; }
        public int F_ComisionAgencia { get; set; }
        public int F_GastosDespacho { get; set; }
        public int F_Verificacion { get; set; }
    }
}
