//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmTraspaso
    {
        public string IndTraspP { get; set; }
        public int CodSucursal { get; set; }
        public int CodAlmSale { get; set; }
        public int CodAlmIng { get; set; }
        public System.DateTime FecTrasp { get; set; }
        public System.DateTime HorTrasp { get; set; }
        public int IdEncargado { get; set; }
        public string Glosa { get; set; }
        public string Transporte { get; set; }
        public string Transportista { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaReg { get; set; }
        public int Consolidado { get; set; }
        public Nullable<int> CodComp { get; set; }
        public string CodGestion { get; set; }
        public string TipoComp { get; set; }
    }
}
