//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmTraspasoZonaFranca
    {
        public string IndTraspZF { get; set; }
        public int CodSucursal { get; set; }
        public string CodTraspTrans { get; set; }
        public int CodAlmSale { get; set; }
        public int CodAlmIng { get; set; }
        public int Moneda { get; set; }
        public System.DateTime FecTrasp { get; set; }
        public System.DateTime HorTrasp { get; set; }
        public double TC { get; set; }
        public string IdEncargado { get; set; }
        public string Glosa { get; set; }
        public string NroEquipo { get; set; }
        public string CodProvTransp { get; set; }
        public double GastoTranspSus { get; set; }
        public double GastoTranspBs { get; set; }
        public int ProrrateoTransporte { get; set; }
        public string CodProvPuerto { get; set; }
        public string Puerto { get; set; }
        public double GastoPuertoSus { get; set; }
        public double GastoPuertoBs { get; set; }
        public int ProrrateoPuerto { get; set; }
        public string CodProvFrontera { get; set; }
        public string PuertoFrontera { get; set; }
        public double GastoFronteraSus { get; set; }
        public double GastoFronteraBs { get; set; }
        public int ProrrateoFrontera { get; set; }
        public string AduanaLlegada { get; set; }
        public string CodProvOtrosG { get; set; }
        public double OtroGastoSus { get; set; }
        public double OtroGastoBs { get; set; }
        public int ProrrateoOtros { get; set; }
        public int ComprDiario { get; set; }
        public string CodGestion { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaReg { get; set; }
    }
}
