//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmTraspasoEnTransito
    {
        public string IndTraspP { get; set; }
        public int CodSucursal { get; set; }
        public string CodIngreso { get; set; }
        public int CodAlmSale { get; set; }
        public int CodAlmIng { get; set; }
        public System.DateTime FecTrasp { get; set; }
        public System.DateTime HorTrasp { get; set; }
        public double TC { get; set; }
        public string IdEncargado { get; set; }
        public string Glosa { get; set; }
        public string NroEquipo { get; set; }
        public string CodProvTransp { get; set; }
        public double CostoTransporteSus { get; set; }
        public double CostoTransporteBs { get; set; }
        public int ProrrateoTransporte { get; set; }
        public string CodProvSeguro { get; set; }
        public string DocSeguro { get; set; }
        public double CostoSeguroSus { get; set; }
        public double CostoSeguroBs { get; set; }
        public int ProrrateoSeguro { get; set; }
        public System.DateTime FechaRealEmbarque { get; set; }
        public System.DateTime FechaLlegada { get; set; }
        public string DocBL { get; set; }
        public string NroBL { get; set; }
        public string DocFactura { get; set; }
        public string NroFactura { get; set; }
        public string CodProv { get; set; }
        public string DocListaEmpaque { get; set; }
        public int Moneda { get; set; }
        public string CodProvOtros { get; set; }
        public string OtroGasto { get; set; }
        public double OtroCostoSus { get; set; }
        public double OtroCostoBs { get; set; }
        public int ComprDiario { get; set; }
        public string CodGestion { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaReg { get; set; }
        public Nullable<int> F_Transporte { get; set; }
        public Nullable<int> F_Seguro { get; set; }
        public Nullable<int> F_OtrosCostos { get; set; }
    }
}
