//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaVendedorH
    {
        public int CodCategoria { get; set; }
        public string CodPersona { get; set; }
        public System.DateTime FIni { get; set; }
        public Nullable<System.DateTime> FFin { get; set; }
        public string Obs { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual CategoriaVendedor CategoriaVendedor { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
