//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clausula1
    {
        public int CodContrato { get; set; }
        public int NroClausula { get; set; }
        public string DesClausula { get; set; }
        public string DesCla { get; set; }
        public byte[] upsize_ts { get; set; }
        public string Titulo { get; set; }
    }
}
