//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratosLegale
    {
        public int NroContrato { get; set; }
        public Nullable<short> TipoContrato { get; set; }
        public string DesContrato { get; set; }
        public string NombreContrato { get; set; }
    }
}
