//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionDetalle
    {
        public string CodCtz { get; set; }
        public string CodProducto { get; set; }
        public string CodProveedor { get; set; }
        public double Cant { get; set; }
        public double Precio { get; set; }
        public double PrecioSus { get; set; }
        public int Aceptado { get; set; }
        public string Obs { get; set; }
    
        public virtual Cotizacion Cotizacion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
