//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaporCobraDeMora
    {
        public string Codigo { get; set; }
        public string CodCliente { get; set; }
        public int TipoDoc { get; set; }
        public string Doc { get; set; }
        public double TasaCambio { get; set; }
        public System.DateTime FechaVent { get; set; }
        public string Glosa { get; set; }
        public int TipoTransaccion { get; set; }
        public int CantDiasCredito { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public double Interes { get; set; }
        public int NroCuotas { get; set; }
        public string TipoCuota { get; set; }
        public Nullable<double> MontoCuota { get; set; }
        public Nullable<double> TotalSus { get; set; }
        public Nullable<double> TotalBs { get; set; }
        public string Estado { get; set; }
        public int Moneda { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuaReg { get; set; }
        public string CodCCosto { get; set; }
        public string CodSubCCosto { get; set; }
        public int TipoCtaPorCobrar { get; set; }
    }
}
