//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaxPagar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CtaxPagar()
        {
            this.CtaxPagarCCs = new HashSet<CtaxPagarCC>();
            this.CtaxPagarDets = new HashSet<CtaxPagarDet>();
        }
    
        public string Codigo { get; set; }
        public string CodProv { get; set; }
        public int Tipo { get; set; }
        public string Doc { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Concepto { get; set; }
        public System.DateTime FechaPagoEstimada { get; set; }
        public double TotalSus { get; set; }
        public double TotalBs { get; set; }
        public int Estado { get; set; }
        public int ComprDiario { get; set; }
        public string CodGestion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuaReg { get; set; }
        public System.DateTime FechaModif { get; set; }
        public string UsuaModif { get; set; }
        public string NroOrdenCompra { get; set; }
        public string AutorizadoP { get; set; }
        public string NroDoc { get; set; }
        public int CIVA { get; set; }
        public int TerminoPago { get; set; }
        public int Bancarizable { get; set; }
        public Nullable<float> ICE { get; set; }
        public Nullable<float> Excentos { get; set; }
        public Nullable<long> Autorizacion { get; set; }
        public string CodControl { get; set; }
        public string NroPlanillaGastos { get; set; }
        public Nullable<int> Tercero { get; set; }
        public string NIT { get; set; }
        public Nullable<int> TipoCompra { get; set; }
        public Nullable<float> ImpNetoIva { get; set; }
        public Nullable<double> TC { get; set; }
        public string CodCCosto { get; set; }
        public string CodSubCCosto { get; set; }
        public string CodProvTercero { get; set; }
        public Nullable<System.DateTime> FechaLimite { get; set; }
        public Nullable<int> DiasPlazo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtaxPagarCC> CtaxPagarCCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtaxPagarDet> CtaxPagarDets { get; set; }
        public virtual TipoCxPagar TipoCxPagar { get; set; }
    }
}
