//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaxPagarDet
    {
        public string Codigo { get; set; }
        public int Nro { get; set; }
        public string TipoPago { get; set; }
        public System.DateTime FechaPago { get; set; }
        public double TotalSus { get; set; }
        public double TotalBs { get; set; }
        public string Obs { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuaReg { get; set; }
        public int ComprDiario { get; set; }
        public string CodGestion { get; set; }
        public string Cajero { get; set; }
        public string RevisadoP { get; set; }
        public string PagadoA { get; set; }
        public Nullable<int> Diario { get; set; }
        public string CodPago { get; set; }
        public string NITFinanciera { get; set; }
        public Nullable<int> TipoDocPago { get; set; }
        public string NroDocPago { get; set; }
    
        public virtual CtaxPagar CtaxPagar { get; set; }
    }
}
