//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaxPagarCC
    {
        public string CodCtaxPagar { get; set; }
        public string CodCC { get; set; }
        public double Porcentaje { get; set; }
        public string Cuenta { get; set; }
        public string CodSubCC { get; set; }
        public decimal MontoBs { get; set; }
        public decimal MontoSus { get; set; }
    
        public virtual CtaxPagar CtaxPagar { get; set; }
    }
}
