//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaClienteMov
    {
        public int CodDeposito { get; set; }
        public int CodCuenta { get; set; }
        public System.DateTime FechaIng { get; set; }
        public short TipoPago { get; set; }
        public string CodCajaIn { get; set; }
        public string CodIngreso { get; set; }
        public string CodUsua { get; set; }
        public double MontoSus { get; set; }
        public double MontoBs { get; set; }
        public string Deb_Hab { get; set; }
        public string Glosa { get; set; }
        public int Disponible { get; set; }
        public int Consolidado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public int ComprDiario { get; set; }
        public string CodGestion { get; set; }
        public string TipoComp { get; set; }
        public string CodProducto { get; set; }
    
        public virtual CuentaCliente CuentaCliente { get; set; }
    }
}
