//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuento
    {
        public int CodDesc { get; set; }
        public string TipoCliente { get; set; }
        public int CodDivision { get; set; }
        public int Contado { get; set; }
        public int Proforma { get; set; }
        public int CodTipoVenta { get; set; }
        public double CantMayorA { get; set; }
        public double MontoMayorA { get; set; }
        public double Descuento1 { get; set; }
    }
}
