//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallePagoCredito2
    {
        public int codSucCaja { get; set; }
        public int codSucursal { get; set; }
        public string Codigo { get; set; }
        public int tipoPago { get; set; }
        public int NroPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Dias { get; set; }
        public Nullable<double> MontoSus { get; set; }
        public Nullable<double> MontoBs { get; set; }
        public int NroCuota { get; set; }
    }
}
