//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePagoCredito
    {
        public string CodCajaIng { get; set; }
        public int CodSucCaja { get; set; }
        public int CodSucursal { get; set; }
        public string CodVenta { get; set; }
        public int TipoPago { get; set; }
        public int NroPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Dias { get; set; }
        public double MontoSus { get; set; }
        public double MontoBs { get; set; }
        public Nullable<int> Division { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<int> Consolidado { get; set; }
        public int Id { get; set; }
    }
}
