//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePagInicProforma
    {
        public string CodProforma { get; set; }
        public Nullable<int> NroRecibo { get; set; }
        public short TipoPago { get; set; }
        public Nullable<double> Monto { get; set; }
        public string Glosa { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
    }
}
