//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReserva
    {
        public string CodReserva { get; set; }
        public string CodProducto { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<int> TipoCliente { get; set; }
        public Nullable<double> CostoEgreso { get; set; }
        public double PrecioUnitario { get; set; }
        public double Cantidad { get; set; }
        public Nullable<double> PorcentajeDescuento { get; set; }
        public Nullable<double> MontoDescuento { get; set; }
        public Nullable<int> CodAlmacen { get; set; }
    
        public virtual Reserva Reserva { get; set; }
    }
}
