//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        public string CodDevolucion { get; set; }
        public int CodSucursal { get; set; }
        public string CodVenta { get; set; }
        public string CodCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public string AutorizadoPor { get; set; }
        public string RegistradoPor { get; set; }
        public string Glosa { get; set; }
        public string Estado { get; set; }
        public string CodSalida { get; set; }
        public string CodIngreso { get; set; }
        public string CodAbono { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaMod { get; set; }
        public string IdUsuaMod { get; set; }
        public int ComprDevol { get; set; }
        public string CodGestionD { get; set; }
    }
}
