//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FondoFijoReposicion
    {
        public string CodPersona { get; set; }
        public int NumReposicion { get; set; }
        public string NumTesoreria { get; set; }
        public int TipoDoc { get; set; }
        public int NroDoc { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal MontoBs { get; set; }
        public decimal MontoSus { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaModif { get; set; }
        public string UsuarioModif { get; set; }
    
        public virtual FondoFijo FondoFijo { get; set; }
    }
}
