//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FondoFijo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FondoFijo()
        {
            this.FondoFijoReposicions = new HashSet<FondoFijoReposicion>();
        }
    
        public string CodPersona { get; set; }
        public string CodCuenta { get; set; }
        public string CodCCosto { get; set; }
        public string CodSubCCosto { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaModif { get; set; }
        public string UsuarioModif { get; set; }
    
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FondoFijoReposicion> FondoFijoReposicions { get; set; }
    }
}
