//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeDiario
    {
        public int CodInforme { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdVendedor { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaReg { get; set; }
    }
}
