//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresosCab
    {
        public int CodSucursal { get; set; }
        public string CodIngreso { get; set; }
        public int TipoIngreso { get; set; }
        public System.DateTime FecIngreso { get; set; }
        public double TC { get; set; }
        public string CodProv { get; set; }
        public string Obs { get; set; }
        public string IdPlanillaConf { get; set; }
        public string OrdenCV { get; set; }
        public string Cotizacion { get; set; }
        public string NroFactura { get; set; }
        public int TipoN { get; set; }
        public string NroTipoN { get; set; }
        public string UsarEn { get; set; }
        public int Moneda { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FecReg { get; set; }
        public int GuardadoOk { get; set; }
        public int Consolidado { get; set; }
        public System.DateTime FechaMod { get; set; }
        public string IdUsuaMod { get; set; }
        public int ComprDiario { get; set; }
        public string CodGestion { get; set; }
    }
}
