//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaGasto
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string CodCuenta { get; set; }
        public bool CtasxPagar { get; set; }
        public bool Rendiciones { get; set; }
        public bool Tesoreria { get; set; }
        public bool CtasPorCobrar { get; set; }
        public string UsuarioReg { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuarioModif { get; set; }
        public System.DateTime FechaModif { get; set; }
    }
}
