//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manzana
    {
        public string CodManzana { get; set; }
        public int CodProy { get; set; }
    
        public virtual Manzana Manzana1 { get; set; }
        public virtual Manzana Manzana2 { get; set; }
    }
}
