//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenCompra()
        {
            this.OrdenCompraDetalles = new HashSet<OrdenCompraDetalle>();
        }
    
        public string IdOrdeCompra { get; set; }
        public System.DateTime FecOC { get; set; }
        public double TC { get; set; }
        public int Moneda { get; set; }
        public string IdPedido { get; set; }
        public string IdCotizacion { get; set; }
        public int IdProyecto { get; set; }
        public string IDCCosto { get; set; }
        public double PorDscto { get; set; }
        public string CodProvP { get; set; }
        public short TerminoPago { get; set; }
        public short TerminoPagoDias { get; set; }
        public short TerminoEntrega { get; set; }
        public short TerminoEntregaDias { get; set; }
        public System.DateTime FecLiminteEntrega { get; set; }
        public string LugarEntrega { get; set; }
        public System.DateTime FechaLimitePedido { get; set; }
        public System.DateTime FechaEnvioAlProv { get; set; }
        public string PlazoDeConfirmacion { get; set; }
        public string ProvResponsable { get; set; }
        public string DirectorEjecutivo { get; set; }
        public string Glosa { get; set; }
        public string SolicitadoP { get; set; }
        public string RevisadoP { get; set; }
        public string AutorizadoP { get; set; }
        public short Estado { get; set; }
        public short CanImpresion { get; set; }
        public int Consolidado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaMod { get; set; }
        public string IdUsuaMod { get; set; }
        public string NroCheque { get; set; }
        public string EntidadFinanciera { get; set; }
        public int ComprDiario { get; set; }
        public string CodGestion { get; set; }
        public string IDSubCosto { get; set; }
        public int Servicio { get; set; }
        public int TieneAnticipo { get; set; }
        public string ObsGral { get; set; }
        public Nullable<int> CodCompDev { get; set; }
        public string CodGesDev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraDetalle> OrdenCompraDetalles { get; set; }
    }
}
