//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompraDetalle
    {
        public string IdOC { get; set; }
        public string IdProd { get; set; }
        public int UnidadOc { get; set; }
        public double CantOc { get; set; }
        public double PrecUnitBs { get; set; }
        public double PrecUnitUs { get; set; }
        public short Estado { get; set; }
        public string Obs { get; set; }
        public string CuentaPresupuesto { get; set; }
    
        public virtual OrdenCompra OrdenCompra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
