//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagosdesc
    {
        public string Codigo { get; set; }
        public Nullable<double> NoCuota { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> CapitalN { get; set; }
        public Nullable<double> InteresN { get; set; }
        public Nullable<double> TotalN { get; set; }
    }
}
