//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedidoDetalles = new HashSet<PedidoDetalle>();
        }
    
        public string CodPedido { get; set; }
        public System.DateTime Fecha { get; set; }
        public double TC { get; set; }
        public int Moneda { get; set; }
        public string CodCCosto { get; set; }
        public int CodProyecto { get; set; }
        public string Glosa { get; set; }
        public string SolicitadoPor { get; set; }
        public string AutorizadoPor { get; set; }
        public Nullable<System.DateTime> FechaAuroriz { get; set; }
        public short Estado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaMod { get; set; }
        public string IdUsuaMod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalles { get; set; }
    }
}
