//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIODO
    {
        public string Codperiodo { get; set; }
        public string Consolidado { get; set; }
        public float Cambiofin { get; set; }
        public float Iva { get; set; }
        public float IT { get; set; }
        public System.DateTime Fechaini { get; set; }
        public System.DateTime Fechafin { get; set; }
        public string Periodofin { get; set; }
        public string codges { get; set; }
    }
}
