//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPagoCtaPCob_A
    {
        public int NroCuota { get; set; }
        public string Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Capital { get; set; }
        public double Interes { get; set; }
        public double TotalCuota { get; set; }
        public double Saldo { get; set; }
        public int Pagado { get; set; }
    
        public virtual CtaPorCobrar_A CtaPorCobrar_A { get; set; }
    }
}
