//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPagoRe
    {
        public string CodRes { get; set; }
        public int NroCuota { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Capital { get; set; }
        public double Interes { get; set; }
        public double TotalCuota { get; set; }
    
        public virtual Reserva Reserva { get; set; }
    }
}
