//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillaConfirmacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanillaConfirmacion()
        {
            this.OrdenCompraConfs = new HashSet<OrdenCompraConf>();
        }
    
        public int CodSucursal { get; set; }
        public string IdPlanillaConf { get; set; }
        public System.DateTime FechaPlanilla { get; set; }
        public string CodProvP { get; set; }
        public string Glosa { get; set; }
        public string NroEquipo { get; set; }
        public string OrdenProvee { get; set; }
        public string FechaProduccion { get; set; }
        public System.DateTime FechaDespacho { get; set; }
        public string PtoEmbarque { get; set; }
        public System.DateTime FechaEmbarque { get; set; }
        public string TipoTrasp { get; set; }
        public string Trasportista { get; set; }
        public string PtoLlegada { get; set; }
        public System.DateTime FechaLlegada { get; set; }
        public int TiempoTransito { get; set; }
        public string INCOTERM { get; set; }
        public string FormaPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public int Moneda { get; set; }
        public string Carga { get; set; }
        public double Volumen { get; set; }
        public double Peso { get; set; }
        public string DocEscaneado { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaMod { get; set; }
        public string IdUsuaMod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraConf> OrdenCompraConfs { get; set; }
    }
}
