//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPagoVentAnt
    {
        public int NroCuota { get; set; }
        public int CodVent { get; set; }
        public int CodSucursal { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Capital { get; set; }
        public double Interes { get; set; }
        public double TotalCuota { get; set; }
        public double Saldo { get; set; }
        public Nullable<double> SaldoCap { get; set; }
        public Nullable<System.DateTime> FechUPago { get; set; }
        public Nullable<double> SaldoIntNorm { get; set; }
        public Nullable<double> SaldoIntVenc { get; set; }
        public Nullable<System.DateTime> FechUPagVenc { get; set; }
        public Nullable<double> SaldoMora { get; set; }
        public Nullable<System.DateTime> FechUPagMora { get; set; }
        public Nullable<double> SaldoEjecucion { get; set; }
        public Nullable<System.DateTime> FechUPagEjec { get; set; }
        public Nullable<double> SaldoIncobrable { get; set; }
        public Nullable<System.DateTime> FechUPagIncob { get; set; }
        public Nullable<int> ComisionJefe { get; set; }
        public Nullable<int> ComisionVendedor { get; set; }
        public int Pagado { get; set; }
    }
}
