//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreAfiliado
    {
        public string CI { get; set; }
        public string NIT { get; set; }
        public string NombreP { get; set; }
        public string Apellido { get; set; }
        public string Seg_Apellido { get; set; }
        public string Ciudad { get; set; }
        public string DireccionDomicilio { get; set; }
        public string DireccionTrabajo { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Sexo { get; set; }
        public string UsuaReg { get; set; }
        public System.DateTime FechaReg { get; set; }
    }
}
