//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestoProducto
    {
        public int CodTramo { get; set; }
        public string CodProducto { get; set; }
        public decimal PrecioUnitBs { get; set; }
        public decimal PrecioUnitSus { get; set; }
        public decimal Cantidad { get; set; }
        public bool Controlado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaModif { get; set; }
        public string UsuarioModif { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Tramo Tramo { get; set; }
    }
}
