//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.AlmacenMovimientoes = new HashSet<AlmacenMovimiento>();
            this.AlmMovImportacions = new HashSet<AlmMovImportacion>();
            this.CotizacionDetalles = new HashSet<CotizacionDetalle>();
            this.OrdenCompraDetalles = new HashSet<OrdenCompraDetalle>();
            this.PedidoDetalles = new HashSet<PedidoDetalle>();
            this.PresupuestoProductos = new HashSet<PresupuestoProducto>();
            this.ProductoConceptoContables = new HashSet<ProductoConceptoContable>();
            this.ProveedorProductoes = new HashSet<ProveedorProducto>();
        }
    
        public string CodProducto { get; set; }
        public string CodBarra { get; set; }
        public string NombreProducto { get; set; }
        public string Descripcion { get; set; }
        public string NroParte { get; set; }
        public int UnidadCompra { get; set; }
        public int UnidadVenta { get; set; }
        public int Equivalencia { get; set; }
        public double Tamanho { get; set; }
        public double Peso { get; set; }
        public double Volumen { get; set; }
        public string Envase { get; set; }
        public Nullable<int> CodProcP { get; set; }
        public int CodMarca { get; set; }
        public int CodSubGrupo { get; set; }
        public double CantMin { get; set; }
        public Nullable<double> PCostoZF { get; set; }
        public double CostoFob { get; set; }
        public double FactorImport { get; set; }
        public double PCosto { get; set; }
        public double Multiplicador { get; set; }
        public double Pventa { get; set; }
        public double PVenta1 { get; set; }
        public double PVenta2 { get; set; }
        public double PVenta3 { get; set; }
        public double PVenta4 { get; set; }
        public int IdTipoPSuper { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<int> IdAplicacion { get; set; }
        public Nullable<int> PagaImp { get; set; }
        public string Observacion { get; set; }
        public int Seriado { get; set; }
        public int Liquidacion { get; set; }
        public int Activo { get; set; }
        public int AceptaReservas { get; set; }
        public int Obsoleto { get; set; }
        public Nullable<int> Rotacion { get; set; }
        public System.DateTime FechaAct { get; set; }
        public string CodUsuario { get; set; }
        public int IdEnvase { get; set; }
        public int IdTecnologia { get; set; }
        public int IdJerarquia { get; set; }
        public int Servicio { get; set; }
        public string Cuenta { get; set; }
        public bool EsLote { get; set; }
        public Nullable<decimal> Superficie { get; set; }
        public Nullable<int> Estadolote { get; set; }
        public string CodUV { get; set; }
        public string CodManzana { get; set; }
        public Nullable<int> CodProyecto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmacenMovimiento> AlmacenMovimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmMovImportacion> AlmMovImportacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionDetalle> CotizacionDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraDetalle> OrdenCompraDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestoProducto> PresupuestoProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoConceptoContable> ProductoConceptoContables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedorProducto> ProveedorProductoes { get; set; }
    }
}
