//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoPrueba
    {
        public string CodProducto { get; set; }
        public string CodBarra { get; set; }
        public string NombreProducto { get; set; }
        public string Descripcion { get; set; }
        public string NroParte { get; set; }
        public int UnidadCompra { get; set; }
        public int UnidadVenta { get; set; }
        public int Equivalencia { get; set; }
        public double Tamanho { get; set; }
        public double Peso { get; set; }
        public double Volumen { get; set; }
        public string Envase { get; set; }
        public int CodProcP { get; set; }
        public int CodMarca { get; set; }
        public int CodSubGrupo { get; set; }
        public double CantMin { get; set; }
        public double PCostoZF { get; set; }
        public double CostoFob { get; set; }
        public double FactorImport { get; set; }
        public double PCosto { get; set; }
        public double Multiplicador { get; set; }
        public double Pventa { get; set; }
        public double PVenta1 { get; set; }
        public double PVenta2 { get; set; }
        public double PVenta3 { get; set; }
        public double PVenta4 { get; set; }
        public int IdTipoPSuper { get; set; }
        public int IdTipo { get; set; }
        public int IdAplicacion { get; set; }
        public int PagaImp { get; set; }
        public string Observacion { get; set; }
        public int Seriado { get; set; }
        public int Liquidacion { get; set; }
        public int Activo { get; set; }
        public int AceptaReservas { get; set; }
        public int Obsoleto { get; set; }
        public int Rotacion { get; set; }
        public System.DateTime FechaAct { get; set; }
        public string CodUsuario { get; set; }
        public int IdEnvase { get; set; }
        public int IdTecnologia { get; set; }
        public int IdJerarquia { get; set; }
        public int Servicio { get; set; }
    }
}
