//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proforma
    {
        public string CodProforma { get; set; }
        public int CodProyecto { get; set; }
        public string CodCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Contacto { get; set; }
        public int TipoCliente { get; set; }
        public double TasaCambio { get; set; }
        public System.DateTime FechaProf { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public System.DateTime FechaVencProf { get; set; }
        public string IdVendedor { get; set; }
        public int CodSucursal { get; set; }
        public int ConFactura { get; set; }
        public int TipoVenta { get; set; }
        public string Glosa { get; set; }
        public int TipoTransaccion { get; set; }
        public double Interes { get; set; }
        public string TipoCuota { get; set; }
        public int NroCuotas { get; set; }
        public double MontoCuota { get; set; }
        public double TotalCredito { get; set; }
        public double TotalSDesc { get; set; }
        public double PorcentajeDescuento { get; set; }
        public double MontoDescuento { get; set; }
        public double TotalCDesc { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaReg { get; set; }
        public int Guardado { get; set; }
        public int Consolidado { get; set; }
        public string CorrelatVend { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public int CantDiasCredito { get; set; }
        public Nullable<double> MontoReservaSus { get; set; }
        public Nullable<double> MontoReservaBs { get; set; }
        public Nullable<int> TipoProforma { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string UsuarioAnulacion { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
    }
}
