//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.Contratoes = new HashSet<Contrato>();
            this.NivelMLMs = new HashSet<NivelMLM>();
            this.Proformas = new HashSet<Proforma>();
        }
    
        public int CodProy { get; set; }
        public string NomProy { get; set; }
        public int Niveles { get; set; }
        public bool Estado { get; set; }
        public int CantManzanas { get; set; }
        public Nullable<double> Interes { get; set; }
        public Nullable<double> PorcInicial { get; set; }
        public bool FCarga { get; set; }
        public string CodCCosto { get; set; }
        public int CantAnios { get; set; }
        public int CuotasAnio { get; set; }
        public Nullable<double> PorcCuotaInicalSocio { get; set; }
        public Nullable<double> PorcCuotaInicialPyR { get; set; }
        public Nullable<double> PorcTotalCreditoSocio { get; set; }
        public Nullable<double> PorcTotalCreditoPyR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contratoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NivelMLM> NivelMLMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proforma> Proformas { get; set; }
    }
}
