//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendicion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rendicion()
        {
            this.RendicionDetalles = new HashSet<RendicionDetalle>();
        }
    
        public int CodRendicion { get; set; }
        public System.DateTime FechaRend { get; set; }
        public string CodResponsable { get; set; }
        public string CodCuenta { get; set; }
        public string CodCC { get; set; }
        public string CodSubCC { get; set; }
        public int Estado { get; set; }
        public int CodComp { get; set; }
        public string CodGestion { get; set; }
        public string UsuaReg { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuaModif { get; set; }
        public Nullable<System.DateTime> FechaModif { get; set; }
        public double MontoBs { get; set; }
        public double MontoSus { get; set; }
        public Nullable<int> CodTesoreriaTrans { get; set; }
        public string Glosa { get; set; }
        public string TipoComp { get; set; }
    
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionDetalle> RendicionDetalles { get; set; }
    }
}
