//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepCtaxPagar
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Reporte { get; set; }
        public Nullable<int> Orden { get; set; }
        public bool VerReporte { get; set; }
        public bool F1 { get; set; }
        public bool F2 { get; set; }
        public bool Proveedor { get; set; }
        public bool Cuenta { get; set; }
        public bool CodComp { get; set; }
        public bool TipoComp { get; set; }
        public bool CodPago { get; set; }
        public bool CodPeriodo { get; set; }
        public bool Exportar { get; set; }
        public bool FPosterior { get; set; }
    }
}
