//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepTesoreria
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Reporte { get; set; }
        public Nullable<int> Orden { get; set; }
        public bool Tesoreria { get; set; }
        public bool Responsable { get; set; }
        public bool NroComprobante { get; set; }
        public bool Moneda { get; set; }
        public bool btnReporte { get; set; }
    }
}
