//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.DetallePagInicReservas = new HashSet<DetallePagInicReserva>();
            this.DetalleReservas = new HashSet<DetalleReserva>();
            this.PlanPagoRes = new HashSet<PlanPagoRe>();
        }
    
        public Nullable<int> CodProforma { get; set; }
        public Nullable<int> TipoCliente { get; set; }
        public string CodReserva { get; set; }
        public string CodCliente { get; set; }
        public Nullable<double> TasaCambio { get; set; }
        public System.DateTime FechaRes { get; set; }
        public Nullable<System.DateTime> FechaVencRes { get; set; }
        public string IdVendedor { get; set; }
        public int CodSucursal { get; set; }
        public int ConFactura { get; set; }
        public string Glosa { get; set; }
        public Nullable<int> TipoVenta { get; set; }
        public int TipoTransaccion { get; set; }
        public double Interes { get; set; }
        public string TipoCuota { get; set; }
        public int NroCuotas { get; set; }
        public Nullable<double> MontoCuota { get; set; }
        public Nullable<double> FechaLimCredito { get; set; }
        public double TotalCredito { get; set; }
        public Nullable<double> TotalSDesc { get; set; }
        public Nullable<double> PorcentajeDescuento { get; set; }
        public Nullable<double> MontoDescuento { get; set; }
        public Nullable<double> TotalCDesc { get; set; }
        public string Estado { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaReg { get; set; }
        public int Consolidado { get; set; }
        public int Guardado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePagInicReserva> DetallePagInicReservas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReserva> DetalleReservas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanPagoRe> PlanPagoRes { get; set; }
    }
}
