//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidasCab
    {
        public Nullable<int> CodSucursal { get; set; }
        public string CodSalida { get; set; }
        public int TipoSalida { get; set; }
        public Nullable<System.DateTime> FecSalida { get; set; }
        public Nullable<double> TC { get; set; }
        public string CodCliente { get; set; }
        public string Obs { get; set; }
        public string NroVenta { get; set; }
        public string NroFactura { get; set; }
        public Nullable<int> Moneda { get; set; }
        public string UsarEn { get; set; }
        public string IdUsua { get; set; }
        public Nullable<System.DateTime> FecReg { get; set; }
        public int Consolidado { get; set; }
        public int GuardadoOk { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public string IdUsuaMod { get; set; }
        public Nullable<int> ComprDiario { get; set; }
        public string CodGestion { get; set; }
    }
}
