//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesProductosBaja
    {
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string CodProducto { get; set; }
        public string NroMotor { get; set; }
        public string NroChasis { get; set; }
        public string NroPoliza { get; set; }
        public string Color { get; set; }
        public string Estado { get; set; }
        public int Vendido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int CodAlmacen { get; set; }
        public int Reservado { get; set; }
        public Nullable<double> PCompra { get; set; }
        public Nullable<double> PVenta { get; set; }
        public string Procedencia { get; set; }
    }
}
