//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeriesProducto()
        {
            this.VentaSerieProductoes = new HashSet<VentaSerieProducto>();
        }
    
        public string CodProducto { get; set; }
        public string NroMotor { get; set; }
        public string NroChasis { get; set; }
        public string NroPoliza { get; set; }
        public string Color { get; set; }
        public int IdAlmacen { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Vendido { get; set; }
        public Nullable<int> Reservado { get; set; }
        public Nullable<double> PCompra { get; set; }
        public Nullable<double> PCompraSus { get; set; }
        public Nullable<double> PVenta { get; set; }
        public Nullable<double> PVentaSus { get; set; }
        public string Procedencia { get; set; }
        public Nullable<int> Consolidado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaSerieProducto> VentaSerieProductoes { get; set; }
    }
}
