//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesMovimiento
    {
        public string Comprobante { get; set; }
        public string TipoMov { get; set; }
        public string CodProducto { get; set; }
        public int CodAlmacen { get; set; }
        public string NroMotor { get; set; }
        public string NroChasis { get; set; }
        public string NroPoliza { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> Fec { get; set; }
        public Nullable<System.DateTime> Hor { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> FecReg { get; set; }
        public string CodUsuario { get; set; }
        public Nullable<int> consolidado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
    }
}
