//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public int CodSucursal { get; set; }
        public string NomSucursal { get; set; }
        public string DirSucursal { get; set; }
        public string Dpto { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> codigocuentacaja { get; set; }
        public Nullable<int> codigocuentaalm { get; set; }
        public Nullable<byte> Activo { get; set; }
        public string NombreCorto { get; set; }
    }
}
