//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMainMenuChoicesUsuario
    {
        public string RootID { get; set; }
        public string SortSequence { get; set; }
        public string Description { get; set; }
        public string CodeToRun { get; set; }
        public Nullable<int> PicID { get; set; }
        public int TopicUniqueID { get; set; }
        public Nullable<int> IdArea { get; set; }
    }
}
