//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tesoreria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tesoreria()
        {
            this.FlujoEfectivoes = new HashSet<FlujoEfectivo>();
            this.Tesoreria_Trans = new HashSet<Tesoreria_Trans>();
        }
    
        public string NroTesoreria { get; set; }
        public string Descripcion { get; set; }
        public string CtaContable { get; set; }
        public Nullable<int> banco { get; set; }
        public Nullable<bool> Moneda { get; set; }
        public Nullable<int> IdCaja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlujoEfectivo> FlujoEfectivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tesoreria_Trans> Tesoreria_Trans { get; set; }
    }
}
