//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tesoreria_Trans
    {
        public int Numero { get; set; }
        public string NroTesoreria { get; set; }
        public int CodSucursal { get; set; }
        public int TipoDoc { get; set; }
        public string DocOrigen { get; set; }
        public string CodPersona { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Hor { get; set; }
        public string DebHab { get; set; }
        public string Glosa { get; set; }
        public int TipoTransacc { get; set; }
        public double MontoUs { get; set; }
        public double MontoBs { get; set; }
        public string CodUsua { get; set; }
        public System.DateTime FecReg { get; set; }
        public string ComprobContab { get; set; }
        public string CodGestionD { get; set; }
        public string TipoComprobContab { get; set; }
        public Nullable<int> Revertido { get; set; }
        public Nullable<int> TipoEgreso { get; set; }
        public decimal TC { get; set; }
        public Nullable<int> NroChequera { get; set; }
    
        public virtual Tesoreria Tesoreria { get; set; }
    }
}
