//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportista
    {
        public int CodTrans { get; set; }
        public string Nombre { get; set; }
        public string Dir { get; set; }
        public string Fono { get; set; }
        public string RuCI { get; set; }
        public Nullable<short> Tipo { get; set; }
        public string Estado { get; set; }
        public string Obs { get; set; }
    }
}
