//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.DetallePagInicVentas = new HashSet<DetallePagInicVenta>();
            this.DetalleVentas = new HashSet<DetalleVenta>();
        }
    
        public string CodCliente { get; set; }
        public string CodVenta { get; set; }
        public int CodSucursal { get; set; }
        public double TasaCambio { get; set; }
        public System.DateTime FechaVent { get; set; }
        public string IdVendedor { get; set; }
        public int CodAlmacen { get; set; }
        public int TipoVenta { get; set; }
        public string OrdenCompra { get; set; }
        public string NroProforma { get; set; }
        public int NroReserva { get; set; }
        public string NIT { get; set; }
        public string Facturar_A { get; set; }
        public string Recoge { get; set; }
        public string VendedorExterno { get; set; }
        public string Glosa { get; set; }
        public int TipoTransaccion { get; set; }
        public int CantDiasCredito { get; set; }
        public Nullable<System.DateTime> FechaLimite { get; set; }
        public double Interes { get; set; }
        public int NroCuotas { get; set; }
        public string TipoCuota { get; set; }
        public double MontoCuota { get; set; }
        public double TotalCredito { get; set; }
        public string Estado { get; set; }
        public int Moneda { get; set; }
        public int Impresa { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string IdUsua { get; set; }
        public System.DateTime FechaMod { get; set; }
        public string IdUsuaMod { get; set; }
        public int Proforma { get; set; }
        public int Anulado { get; set; }
        public int Consolidado { get; set; }
        public int ComprDiario { get; set; }
        public string CodGestion { get; set; }
        public int ComprDevol { get; set; }
        public string CodGestionD { get; set; }
        public int VentaServicio { get; set; }
        public string CodCCosto { get; set; }
        public string CodSubCCosto { get; set; }
        public Nullable<System.DateTime> FechaPagoM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePagInicVenta> DetallePagInicVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVentas { get; set; }
    }
}
