//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaSerieProducto
    {
        public string CodVenta { get; set; }
        public int CodSucursal { get; set; }
        public string CodProducto { get; set; }
        public string NroMotor { get; set; }
        public string NroChasis { get; set; }
        public string NroPoliza { get; set; }
        public string Color { get; set; }
        public Nullable<int> Devuelto { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<int> Consolidado { get; set; }
    
        public virtual SeriesProducto SeriesProducto { get; set; }
    }
}
