//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vwt_TotalClienteMora
    {
        public string CodCliente { get; set; }
        public string NombreCompleto { get; set; }
        public string Codigo { get; set; }
        public string CodMora { get; set; }
        public Nullable<double> Interes { get; set; }
        public Nullable<int> TotalCuota { get; set; }
    }
}
