//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.INVENTARIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vwt_DetalleCantidadMora
    {
        public string Codigo { get; set; }
        public string CodCliente { get; set; }
        public double MontoCuota { get; set; }
        public int NroCuota { get; set; }
        public string CodMora { get; set; }
        public Nullable<double> SaldoCuota { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
