//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.USER
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsignacionCliente()
        {
            this.Cuotas = new HashSet<Cuota>();
            this.OperacionCobranzas = new HashSet<OperacionCobranza>();
        }
    
        public int asignacionClienteID { get; set; }
        public string CodCliente { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public string UsrCre { get; set; }
        public string UsrMod { get; set; }
        public Nullable<System.DateTime> FeCre { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> CodUsuario { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaReasignacion { get; set; }
        public string Periodo { get; set; }
        public string Codigo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuota> Cuotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacionCobranza> OperacionCobranzas { get; set; }
    }
}
