//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.USER
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotiPreventivo
    {
        public int NotificacionID { get; set; }
        public string CodCliente { get; set; }
        public string Periodo { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> TipoAccion { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string UsrCre { get; set; }
    }
}
