//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.USER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vwt_vistaoperacion
    {
        public int asignacionClienteID { get; set; }
        public string CodCliente { get; set; }
        public string NombreCompleto { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> CodUsuario { get; set; }
        public string NombreCobrador { get; set; }
        public int operacionCobranzaID { get; set; }
        public string Comentario { get; set; }
        public string TelefonoAlternativo { get; set; }
        public Nullable<System.DateTime> FechaCompromiso { get; set; }
        public Nullable<System.DateTime> FeCre { get; set; }
        public Nullable<System.DateTime> FeMod { get; set; }
        public string UsrCre { get; set; }
        public string UsrMod { get; set; }
        public string NombreCuasalMora { get; set; }
        public string NombreCompromisopago { get; set; }
        public string NombreProbalidadPago { get; set; }
        public string NombreParametro { get; set; }
        public string NombreTipoGestion { get; set; }
    }
}
