//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB.DATA.USER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vwt_AsigOpercaion
    {
        public int asignacionClienteID { get; set; }
        public int operacionCobranzaID { get; set; }
        public string Comentario { get; set; }
        public string TelefonoAlternativo { get; set; }
        public Nullable<System.DateTime> FechaCompromiso { get; set; }
        public string CausalMoraAnt { get; set; }
        public Nullable<System.DateTime> FeCre { get; set; }
        public Nullable<System.DateTime> FeMod { get; set; }
        public string UsrCre { get; set; }
        public string UsrMod { get; set; }
        public Nullable<int> causalMoraID { get; set; }
        public Nullable<int> compromisoPagoID { get; set; }
        public Nullable<int> CodUsuario { get; set; }
        public string CodCliente { get; set; }
        public string Periodo { get; set; }
    }
}
